val moduleId by extra("zygisk_gpu_driver_loader")
val moduleName by extra("Zygisk GPU Driver Loader")
val moduleAuthor by extra("NKU100")
val moduleDesc by extra("Load custom Adreno Vulkan drivers per app")
val moduleApplicationId by extra("io.github.nku100.gpudriver")
val moduleLibName by extra("zygisk_gpu_driver_loader")
val abiList by extra(listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64", "riscv64"))
